# Generated by Django 3.2.8 on 2021-12-10 06:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_type',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='image_evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_evidence', models.ImageField(upload_to='landing/images/evidence')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question_form',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_description', models.CharField(default='', max_length=100)),
                ('is_options', models.BooleanField(default=False)),
                ('is_check', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.form_type')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='answer_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('answer', models.TextField(default='')),
                ('created', models.DateField(default=datetime.date.today)),
                ('answer_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form_type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='landing.form_type')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.question_form')),
            ],
        ),
    ]
