# Generated by Django 3.2.8 on 2021-12-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_answer_form_form_type_image_evidence_question_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_evidence',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='image_evidence',
            name='form_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='image_evidence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image_evidence',
            name='image_evidence',
            field=models.ImageField(null=True, upload_to='landing/images/evidence'),
        ),
    ]
